### ISSUE TITLE
[Suggestion] FLAC Download?

### ISSUE THREAD

**Issue by FireWolf700** [RallyTuning/VideoGamesMusic-Downloader#2]
Looks like this GUI is only able to grab the .mp3 version of a soundtrack, so I'll request an option to have the FLAC upload take priority if possible. Thank you for this tool! Works well, and doesn't seem to have any issues otherwise.

**Comment by RallyTuning** [comment]
Hello, thanks for your feedback! I will add this extension too.
Consider to star the project for get the update when i upload new releases.

**Comment by RallyTuning** [comment]
### Approved and done ✅
https://github.com/RallyTuning/VideoGamesMusic-Downloader/releases/tag/v3

**Comment by Aberen** [comment]
Could we get a checkbox in the interface somewhere so you could choose if you want to download FLAC or not?

**Comment by Aberen** [comment]
Crazy fast turnaround! Thanks @RallyTuning!
